### ISSUE TITLE
semantic segmentation.

### ISSUE THREAD

**Issue by kiranintellify** [romaintha/pytorch_pointnet#1]
Hi , Can we use this for sem_seg as well.

**Comment by romaintha** [comment]
Yes you should be able. You can check this blog post for more details:
https://www.qwertee.io/blog/deep-learning-with-point-clouds/

**Comment by kiranintellify** [comment]
Hi , romaintha actually i tried this .This works till part segmentation. How to to do sem_seg .As i it has not mentioned for semantic segmentation.

**Comment by romaintha** [comment]
Well, I might miss something, but I don't see any conceptual difference between semantic and part segmentation. In the original PointNet paper, they have been applying this model to semantic segmentation. The only problem I can see is that the PointNet model does not work very well with large scene because it cannot capture local structure induced by the metric space points live in. I would therefore recommend you to have a look at a PointNet++ implementation.
